[book]
title = "Spydecy - The Self-Hosted Python/C-to-Rust Compiler-Debugger"
authors = ["Spydecy Team"]
description = "Official guide for Spydecy: unified Python and C-to-Rust transpilation with introspective debugging"
language = "en"
multilingual = false
src = "book/src"

[rust]
edition = "2021"

[build]
build-dir = "book/build"
create-missing = true

[preprocessor.links]

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/noahgift/spydecy"
edit-url-template = "https://github.com/noahgift/spydecy/edit/main/{path}"
site-url = "/spydecy/"
cname = "spydecy.dev"

[output.html.fold]
enable = true
level = 1

[output.html.playground]
editable = true
copyable = true
copy-js = true
line-numbers = true
runnable = true
