name: Deploy Book

on:
  push:
    branches: [main]
    paths:
      - 'book/**'
      - 'book.toml'
      - '.github/workflows/book.yml'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test-book-examples:
    name: Test Book Code Examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3.10-dev libclang-14-dev

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-book-${{ hashFiles('**/Cargo.lock') }}

      - name: Install mdbook
        run: |
          cargo install mdbook --vers "^0.4" --locked

      - name: Test book code examples
        run: |
          # mdBook automatically tests code blocks marked with ```rust
          mdbook test book

      - name: Build workspace (ensure examples compile)
        run: cargo build --workspace

  build-and-deploy:
    name: Build and Deploy Book
    needs: test-book-examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install mdbook
        run: |
          cargo install mdbook --vers "^0.4" --locked

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build book
        run: mdbook build book

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './book/build/html'

  deploy:
    name: Deploy to GitHub Pages
    needs: build-and-deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
